language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install
script:
  - vendor/bin/phing
after_script:
  - phpenv config-add xdebug.ini
  - php vendor/bin/coveralls -v
